#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_NAME" <<-EOSQL
    CREATE USER $DB_USER WITH password '$DB_PASSWORD';
    ALTER USER $DB_USER WITH SUPERUSER;
    GRANT ALL PRIVILEGES ON DATABASE postgres TO $DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to $DB_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to $DB_USER;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to $DB_USER;
EOSQL
